input_data:
  file_bea1: "../data/raw/WB_WDI_WIDEF.CSV"
  file_bea2: "../data/raw/WB_HCI_WIDEF.CSV"
  file_bea3: "../data/raw/WB_HCP_EMP_2WAP_A_WIDEF.CSV"

output_data:
  file: "../data/clean/cleaned_data_file.csv"